---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-server
  labels:
    app: hello-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: hello-server
        image: blux2/hello-server:1.2
---
apiVersion: v1
kind: Service
metadata:
  name: hello-server
spec:
  type: ClusterIP
  selector:
    app: hello-server
  ports:
    - port: 8080
      targetPort: 8080
